### ISSUE TITLE
Add Docker CI to existing ubuntu build workflow

### ISSUE THREAD

**Issue by CheatCod** [Lodestone-Team/client#115]
# Description

This way we take advantage of the caching done by the existing workflow and avoid duplicate work.

# Steps to reproduce (optional)

**Comment by Bockiii** [comment]
Hi,

I dont think that what you want is possible. If you establish using --cache-from as a buildx argument, your dockerfile will not be able to be used by anyone else to actually build the image. So no one could just clone your repo and run docker build (because it would be depended on injections from your buildx pipeline).

I would propose a different alternative: Implement an arm build into your build ci that also gets uploaded to release artifacts and rewrite your dockerfile to download a release by version tag that you can then use as an argument for the CI.

This would do the following:
- build CI builds linux, arm64 and windows builds, uploads them to gh releases and tags them.
- docker ci will see a new release and use the tag to build the dockerfile. The Dockerfile is rewritten to ingest a tag, build the download string for gh, download the already built release and start it.

This should bring the docker build down to seconds and you have the benefit of having a downloadable arm release available for users.
